# # # # PECHKATA TIMER # # # #

- alias: On enter second
  trigger:
    platform: time_pattern
    seconds: '/1'
  condition: 
  - condition: numeric_state
    entity_id: input_number.heat_duration
    above: 0
  action:
  - service: input_number.decrement
    entity_id: input_number.heat_duration

- alias: Turn ON pechkata
  trigger:
    platform: numeric_state
    entity_id: input_number.heat_duration
    above: 0
  action:
  - service: scene.turn_on
    entity_id: scene.pechkata_on
  #- service: xiaomi_aqara.play_ringtone
  #  data: { ringtone_vol: 40, ringtone_id: 10013 }

- alias: Turn OFF pechkata
  trigger:
    platform: numeric_state
    entity_id: input_number.heat_duration
    below: 1
  action:
  - service: scene.turn_on
    entity_id: scene.pechkata_off
  - service: xiaomi_aqara.play_ringtone
    data: { ringtone_vol: 60, ringtone_id: 10006 }
      
# # # # TEST # # # #

- alias: test1
  trigger:
    platform: state
    entity_id: binary_sensor.bb_button_1
    to: "on"
  action:
  - service: light.toggle
    entity_id: light.hq_lights
  - service: xiaomi_aqara.play_ringtone
    data: { ringtone_vol: 3, ringtone_id: 10026 }
- alias: test2
  trigger:
    platform: state
    entity_id: binary_sensor.bb_button_2
    to: "on"
  action:
  - service: light.toggle
    entity_id: light.xiaomi_philips_candle
  - service: xiaomi_aqara.play_ringtone
    data: { ringtone_vol: 3, ringtone_id: 10017 }
- alias: test3
  trigger:
    platform: state
    entity_id: binary_sensor.bb_button_3
    to: "on"
  action:
  - service: light.turn_on
    data:
      entity_id: light.xiaomi_philips_candle
      color_temp: 333
  - service: xiaomi_aqara.play_ringtone
    data: { ringtone_vol: 3, ringtone_id: 10017 }
- alias: test4
  trigger:
    platform: state
    entity_id: binary_sensor.bb_button_4
    to: "on"
  action:
  - service: switch.toggle
    entity_id: switch.hass_led
  - service: xiaomi_aqara.play_ringtone
    data: { ringtone_vol: 3, ringtone_id: 10017 }
- alias: test5
  trigger:
    platform: state
    entity_id: binary_sensor.bb_button_5
    to: "on"
  action:
  - service: light.turn_on
    data:
      entity_id: light.xiaomi_philips_candle
      color_temp: 175
  - service: xiaomi_aqara.play_ringtone
    data: { ringtone_vol: 3, ringtone_id: 10017 }
      
# # # # RINGTONES # # # #

- alias: Notify When Hassio Sarts
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: switch.turn_on
    entity_id: switch.hass_led
  - service: xiaomi_aqara.play_ringtone
    data: {ringtone_vol: 50, ringtone_id: 10016 }
    
- alias: Notify When Hassio Starts
  trigger:
  - platform: homeassistant
    event: shutdown
  action:
  - service: xiaomi_aqara.play_ringtone
    data: {ringtone_vol: 50, ringtone_id: 10015 }
  - service: switch.turn_off
    entity_id: switch.hass_led
      
# # # # MOTION # # # #

- alias: PIR Hall - ON
  trigger:
    platform: state
    entity_id: binary_sensor.pir_hall
    to: "on"
  action:
  - service: xiaomi_aqara.play_ringtone
    data: { ringtone_vol: 5, ringtone_id: 10020 }
  - service: light.turn_on
    entity_id: light.wall_ewe61
  - service: light.turn_on
    entity_id: light.xiaomi_philips_candle
    
- alias: PIR Kitchen - ON
  trigger:
    platform: state
    entity_id: binary_sensor.pir_kitchen
    to: "on"
  condition:
    condition: template
    value_template: '{{ states.sun.sun.attributes.elevation < 15 }}'
  action:
  - service: xiaomi_aqara.play_ringtone
    data: { ringtone_vol: 5, ringtone_id: 10020 }
  - service: light.turn_on
    entity_id: light.wall_ewe62
    
- alias: PIR Hall - OFF
  trigger:
    platform: time_pattern
    seconds: '/10'
  condition: 
    condition: and
    conditions:
      - condition: state
        entity_id: light.wall_ewe61
        state: "on"
        for: { minutes: 5 } # seconds minutes
      - condition: state
        entity_id: binary_sensor.pir_hall
        state: "off"
        for: { minutes: 5 } # seconds minutes
  action:
  - service: light.turn_off
    entity_id: light.wall_ewe61

- alias: PIR Kitchen - OFF
  trigger:
    platform: time_pattern
    seconds: '/10'
  condition: 
    condition: and
    conditions:
      - condition: state
        entity_id: light.wall_ewe62
        state: "on"
        for: { minutes: 5 } # seconds minutes
      - condition: state
        entity_id: binary_sensor.pir_kitchen
        state: "off"
        for: { minutes: 5 } # seconds minutes
  action:
  - service: light.turn_off
    entity_id: light.wall_ewe62

# # # # INPUTTA # # # #

- alias: Button BIDABED (single) -- Good Night
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.mi_button_bidabed
      click_type: single
  condition:
    condition: state
    entity_id: light.hq_lights
    state: 'on'
  action:
  - service: script.turn_on
    entity_id: script.lights_off
  - service: xiaomi_aqara.play_ringtone
    data: { ringtone_vol: 25, ringtone_id: 10011 }
  - service: rest_command.pc_sleep
- alias: Button BIDABED (single) -- Good Morning
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.mi_button_bidabed
      click_type: single
  condition:
    condition: state
    entity_id: light.hq_lights
    state: 'off'
  action:
  - service: script.turn_on
    entity_id: script.lights_full
  - service: xiaomi_aqara.play_ringtone
    data: { ringtone_vol: 25, ringtone_id: 10022 }
- alias: Button BIDABED (double) -- Dim dem lites
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.mi_button_bidabed
      click_type: double
  action:
  - service: script.turn_on
    entity_id: script.lights_dimmer
  - service: xiaomi_aqara.play_ringtone
    data: { ringtone_vol: 15, ringtone_id: 10010 }
- alias: Button BIDABED (hold)
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.mi_button_bidabed
      click_type: long_click_press
  action:
  - service: switch.toggle
    entity_id: switch.pechkata

- alias: Button BIDADOR (single)
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.mi_button_bidador
      click_type: single
  action:
  - service: light.toggle
    entity_id: light.hq_lights
  - service: xiaomi_aqara.play_ringtone
    data: { ringtone_vol: 10, ringtone_id: 10019 }
- alias: Button BIDADOR (double)
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.mi_button_bidador
      click_type: double
  action:
  - service: light.turn_off
    entity_id: light.wall_ewe61
  - service: light.turn_off
    entity_id: light.wall_ewe62
  - service: xiaomi_aqara.play_ringtone
    data: { ringtone_vol: 1, ringtone_id: 10029 }
- alias: Button BIDADOR (hold)
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.mi_button_bidador
      click_type: long_click_press
  action:
    service: switch.toggle
    entity_id: switch.pechkata
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      