# # # # PECHKATA TIMER # # # #

- alias: On enter second
  trigger: { platform: time_pattern, seconds: '/1' }
  condition: { condition: numeric_state, entity_id: input_number.heat_duration, above: 0 }
  action: { service: input_number.decrement, entity_id: input_number.heat_duration }

- alias: Turn ON pechkata
  trigger: { platform: numeric_state, entity_id: input_number.heat_duration, above: 0 }
  action: { service: scene.turn_on, entity_id: scene.pechkata_on }

- alias: Turn OFF pechkata
  trigger: { platform: numeric_state, entity_id: input_number.heat_duration, below: 1 }
  action: { service: scene.turn_on, entity_id: scene.pechkata_off }
      
# # # # HACKER BUTTONS # # # #

- alias: Dev Console Button 1
  trigger: { platform: state, entity_id: binary_sensor.bb_button_1, to: "on" }
  action: { service: light.toggle, entity_id: light.hq_lights }
  
- alias: Dev Console Button 2
  trigger: { platform: state, entity_id: binary_sensor.bb_button_2, to: "on" }
  action: { service: light.toggle, entity_id: light.xiaomi_philips_candle }
  
- alias: Dev Console Button 3
  trigger: { platform: state, entity_id: binary_sensor.bb_button_3, to: "on" }
  action: { service: light.turn_on, data: { entity_id: light.xiaomi_philips_candle, color_temp: 333 } }
  
- alias: Dev Console Button 4
  trigger: { platform: state, entity_id: binary_sensor.bb_button_4, to: "on" }
  action: { service: switch.toggle, entity_id: switch.hass_led }
  
- alias: Dev Console Button 5
  trigger: { platform: state, entity_id: binary_sensor.bb_button_5, to: "on" }
  action: { service: light.turn_on, data: { entity_id: light.xiaomi_philips_candle, color_temp: 175 } }
      
# # # # MOTION # # # #

- alias: PIR Hall - ON
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_hall
      to: "on"
  action:
    #- service: light.turn_on
    #  entity_id: light.wall_ewe61
    - service: light.turn_on
      entity_id: light.xiaomi_philips_candle
    
- alias: PIR Kitchen - ON
  trigger:
    - platform: state
      entity_id: binary_sensor.pir_kitchen
      to: "on"
  condition:
    - condition: template
      value_template: '{{ states.sun.sun.attributes.elevation < 15 }}'
  action:
    - service: light.turn_on
      entity_id: light.wall_ewe62
    
- alias: PIR Hall - OFF
  trigger: { platform: time_pattern, seconds: '/10' }
  condition: 
    - condition: and
      conditions:
        - condition: state
          entity_id: light.wall_ewe61
          state: "on"
          for: { minutes: 5 } # seconds minutes
        - condition: state
          entity_id: binary_sensor.pir_hall
          state: "off"
          for: { minutes: 5 } # seconds minutes
  action:
    - service: light.turn_off
      entity_id: light.wall_ewe61

- alias: PIR Kitchen - OFF
  trigger: { platform: time_pattern, seconds: '/10' }
  condition: 
    - condition: and
      conditions:
        - condition: state
          entity_id: light.wall_ewe62
          state: "on"
          for: { minutes: 5 } # seconds minutes
        - condition: state
          entity_id: binary_sensor.pir_kitchen
          state: "off"
          for: { minutes: 5 } # seconds minutes
  action:
    - service: light.turn_off
      entity_id: light.wall_ewe62

# # # # INPUTTA # # # #

- alias: "Button BIDABED (single) -- Good Night"
  condition: 
    condition: state
    entity_id: light.hq_lights
    state: "on"
  trigger: 
    - event_data: 
        click_type: single
        entity_id: binary_sensor.mi_button_bidabed
      event_type: xiaomi_aqara.click
      platform: event
  action: 
    - entity_id: script.lights_off
      service: script.turn_on
    # - service: rest_command.pc_sleep
      
- alias: "Button BIDABED (single) -- Good Morning"
  condition: 
    condition: state
    entity_id: light.hq_lights
    state: "off"
  trigger: 
    - event_data: 
        click_type: single
        entity_id: binary_sensor.mi_button_bidabed
      event_type: xiaomi_aqara.click
      platform: event
  action: 
    - entity_id: script.lights_full
      service: script.turn_on
     
- alias: "Button BIDABED (double) -- Dim dem lites"
  trigger: 
    - event_data: { click_type: double, entity_id: binary_sensor.mi_button_bidabed }
      event_type: xiaomi_aqara.click
      platform: event
  action: 
    - entity_id: script.lights_dimmer
      service: script.turn_on
      
- alias: "Button BIDABED (hold)"
  trigger: 
    - event_data: { click_type: long_click_press, entity_id: binary_sensor.mi_button_bidabed }
      event_type: xiaomi_aqara.click
      platform: event
  action: 
    - entity_id: switch.pechkata
      service: switch.toggle
  
- alias: "Button BIDADOR (single)"
  trigger: 
    - event_data: { click_type: single, entity_id: binary_sensor.mi_button_bidador }
      event_type: xiaomi_aqara.click
      platform: event
  action: 
    - entity_id: light.hq_lights
      service: light.toggle
      
- alias: "Button BIDADOR (double)"
  trigger: 
    - event_data: { click_type: double, entity_id: binary_sensor.mi_button_bidador }
      event_type: xiaomi_aqara.click
      platform: event
  action: 
    - entity_id: light.wall_ewe61
      service: light.turn_off
    - entity_id: light.wall_ewe62
      service: light.turn_off
      
- alias: "Button BIDADOR (hold)"
  trigger: 
    - event_data: { click_type: long_click_press, entity_id: binary_sensor.mi_button_bidador }
      event_type: xiaomi_aqara.click
      platform: event
  action: 
    - entity_id: switch.pechkata
      service: switch.toggle
  
