# # # # HACKER BUTTONS # # # #
# # # # HACKER BUTTONS # # # #
# # # # HACKER BUTTONS # # # #

- alias: "Dev Console Button 1"
  trigger: { platform: state, entity_id: binary_sensor.bb_button_1, to: "on" }
  action: { service: light.toggle, entity_id: light.hq_lights }
  
- alias: "Dev Console Button 2"
  trigger: { platform: state, entity_id: binary_sensor.bb_button_2, to: "on" }
  action: { service: switch.toggle, entity_id: switch.hass_led }
  
- alias: "Dev Console Button 3"
  trigger: { platform: state, entity_id: binary_sensor.bb_button_3, to: "on" }
  action: { service: light.toggle, data: { entity_id: light.xiaomi_philips_candle, color_temp: 333 } }
  
- alias: "Dev Console Button 4"
  trigger: { platform: state, entity_id: binary_sensor.bb_button_4, to: "on" }
  action: { service: homeassistant.turn_off, entity_id: group.all_lights }
  
- alias: "Dev Console Button 5"
  trigger: { platform: state, entity_id: binary_sensor.bb_button_5, to: "on" }
  action: { service: light.turn_on, data: { entity_id: light.xiaomi_philips_candle, color_temp: 175 } }
      
# # # # INPUTTA # # # #
# # # # INPUTTA # # # #
# # # # INPUTTA # # # #

- alias: "Button BIDABED (single) -- Good Night"
  condition: { condition: state,  entity_id: light.hq_lights, state: "on" }
  trigger: 
    - event_data: { entity_id: binary_sensor.mi_button_bidabed, click_type: single }
      event_type: xiaomi_aqara.click
      platform: event
  action: { service: script.turn_on, entity_id: script.lights_off }

- alias: "Button BIDABED (single) -- Good Morning"
  condition: { condition: state,  entity_id: light.hq_lights, state: "off" }
  trigger: 
    - event_data: { entity_id: binary_sensor.mi_button_bidabed, click_type: single }
      event_type: xiaomi_aqara.click
      platform: event
  action: { service: script.turn_on, entity_id: script.lights_full }

- alias: "Button BIDABED (double) -- Dim dem lites"
  condition: { condition: template, value_template: '{{ states.light.hq_lights.attributes.brightness > 149 }}' }
  trigger: 
    - event_data: { click_type: double, entity_id: binary_sensor.mi_button_bidabed }
      event_type: xiaomi_aqara.click
      platform: event
  action: { service: script.turn_on, entity_id: script.lights_dimmer }

- alias: "Button BIDABED (double) -- Undim dem lites"
  condition: { condition: template, value_template: '{{ states.light.hq_lights.attributes.brightness < 150 }}' }
  trigger: 
    - event_data: { click_type: double, entity_id: binary_sensor.mi_button_bidabed }
      event_type: xiaomi_aqara.click
      platform: event
  action: { service: script.turn_on, entity_id: script.lights_full }

- alias: "Button BIDABED (hold)"
  trigger: 
    - event_data: { click_type: long_click_press, entity_id: binary_sensor.mi_button_bidabed }
      event_type: xiaomi_aqara.click
      platform: event
  action: { service: switch.toggle, entity_id: switch.pechkata }

# # # #

- alias: "Button BIDADOR (single) ON"
  trigger: 
    - event_data: { click_type: single, entity_id: binary_sensor.mi_button_bidador }
      event_type: xiaomi_aqara.click
      platform: event
  condition: { condition: state, entity_id: light.hq_lights, state: "off" }
  action: { service: script.turn_on, entity_id: script.lights_full }

- alias: "Button BIDADOR (single) OFF"
  trigger: 
    - event_data: { click_type: single, entity_id: binary_sensor.mi_button_bidador }
      event_type: xiaomi_aqara.click
      platform: event
  condition: { condition: state, entity_id: light.hq_lights, state: "on" }
  action: { service: light.turn_off, entity_id: light.hq_lights }

- alias: "Button BIDADOR (double)"
  trigger: 
    - event_data: { click_type: double, entity_id: binary_sensor.mi_button_bidador }
      event_type: xiaomi_aqara.click
      platform: event
  action: 
    - { service: light.turn_off, entity_id: light.hall_lights }
    - { service: light.turn_off, entity_id: light.wall_ewe62 }
    - { service: light.turn_on,  entity_id: light.xiaomi_philips_candle, data: { color_temp: 333, brightness: 102 } }

- alias: "Button BIDADOR (hold)"
  trigger: 
    - event_data: { click_type: long_click_press, entity_id: binary_sensor.mi_button_bidador }
      event_type: xiaomi_aqara.click
      platform: event
  action: { service: switch.toggle, entity_id: switch.pechkata }



