# # # # HASSIO # # # #

- alias: Refresh Things When Hassio Stats
  trigger: { platform: homeassistant, event: start }
  action: { service: rest_command.tuya_server_refresh }
    
# # # # PECHKATA TIMER # # # #

- alias: On enter second
  trigger: { platform: time_pattern, seconds: '/1' }
  condition: { condition: numeric_state, entity_id: input_number.heat_duration, above: 0 }
  action: { service: input_number.decrement, entity_id: input_number.heat_duration }

- alias: Turn ON pechkata
  trigger: { platform: numeric_state, entity_id: input_number.heat_duration, above: 0 }
  action: { service: switch.turn_on, entity_id: switch.pechkata_plug }

- alias: Turn OFF pechkata
  trigger: { platform: numeric_state, entity_id: input_number.heat_duration, below: 1 }
  action: { service: switch.turn_off, entity_id: switch.pechkata_plug }
      
# # # # MOTION # # # #

- alias: PIR Hall - ON
  trigger: { platform: state, entity_id: binary_sensor.pir_hall, to: "on" }
  action: 
    - { service: light.turn_on, entity_id: light.wall_ewe61 }
    - { service: light.turn_on, entity_id: light.xiaomi_philips_candle, data: { color_temp: 333, brightness: 255 } }
    
- alias: PIR Kitchen - ON
  trigger:  { platform: state, entity_id: binary_sensor.pir_kitchen, to: "on" }
  #condition: { condition: template, value_template: '{{ states.sun.sun.attributes.elevation < 15 }}' }
  action: { service: light.turn_on, entity_id: light.wall_ewe62 }
    
- alias: PIR Hall - OFF
  trigger: { platform: time_pattern, seconds: '/10' }
  condition: 
    - condition: and
      conditions: # seconds minutes
        - { condition: state, entity_id: light.wall_ewe61, state: "on", for: { minutes: 1 } }
        - { condition: state, entity_id: binary_sensor.pir_hall, state: "off", for: { minutes: 1 } }
  action:
    - { service: light.turn_off, entity_id: light.wall_ewe61 }
    - { service: light.turn_on, entity_id: light.xiaomi_philips_candle, data: { color_temp: 333, brightness: 102 } }

- alias: PIR Kitchen - OFF
  trigger: { platform: time_pattern, seconds: '/10' }
  condition: 
    - condition: and
      conditions: # seconds minutes
        - { condition: state, entity_id: light.wall_ewe62, state: "on", for: { minutes: 5 } }
        - { condition: state, entity_id: binary_sensor.pir_kitchen, state: "off", for: { minutes: 10 } }
  action: { service: light.turn_off, entity_id: light.wall_ewe62 }


